### Create a new product
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Test",
  "price": 1
}

### Get all products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/3aab2b37-f308-4322-bd52-1f9032471558

### Update a product
PUT http://localhost:3000/products/01330f4f-a3c4-4825-b01b-42e7082c7852
content-type: application/json

{
    "name": "Updated Product",
    "price": 2.02
}

### Delete a product
DELETE http://localhost:3000/products/01330f4f-a3c4-4825-b01b-42e7082c7852
