version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: nest-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    build: .docker/postgres
    container_name: nest-db
    restart: always
    tty: true
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
  
  grpc-test:
    image: gusaul/grpcox:latest
    ports:
      - 6969:6969
